# Generated by Django 3.0.5 on 2020-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('mob', models.CharField(max_length=50)),
                ('textarea', models.TextField(default='', max_length=10000)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('ed_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('solution', models.TextField(max_length=1500)),
                ('Input', models.TextField(max_length=1000)),
                ('Output', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=50)),
                ('description_1', models.TextField(max_length=5000)),
                ('description_2', models.TextField(max_length=10000)),
                ('description_3', models.TextField(max_length=5000)),
                ('ref_link_1', models.CharField(max_length=100)),
                ('ref_link_2', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='learn/images')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
    ]
