# Generated by Django 3.0.5 on 2020-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
