# Generated by Django 3.0.5 on 2020-05-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('recommended', models.CharField(max_length=50)),
                ('asked', models.CharField(max_length=50)),
                ('answer', models.TextField(default='', max_length=2000)),
                ('Input', models.TextField(max_length=1000)),
                ('Output', models.TextField(max_length=1000)),
                ('starting_point', models.TextField(default='', max_length=500)),
                ('pub_date', models.DateField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
