# Generated by Django 3.0.5 on 2020-05-29 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programming', '0002_program_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.ProgramComment')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProgramComment',
                'verbose_name_plural': 'ProgramComments',
            },
        ),
    ]
