# Generated by Django 3.0.5 on 2020-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_programcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('String', 'STRING'), ('Array', 'ARRAY'), ('List', 'LIST'), ('Linked List', 'LINKED LIST'), ('Tree', 'TREE'), ('Others', 'OTHERS')], max_length=20),
        ),
    ]
